/* Textured page mesh: perspective, curved paper and directional lighting. */
type Point={x:number;y:number};
function triangle(ctx:CanvasRenderingContext2D,img:HTMLImageElement,s:Point[],d:Point[]){const [a,b,c]=s,[p,q,r]=d;const det=(b.x-a.x)*(c.y-a.y)-(c.x-a.x)*(b.y-a.y);if(Math.abs(det)<.001)return;ctx.save();ctx.beginPath();const winding=((q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x))>0?1:-1;for(let i=0;i<3;i++){const v=d[i],prev=d[(i+2)%3],next=d[(i+1)%3];const l1=Math.hypot(v.x-prev.x,v.y-prev.y)||1,l2=Math.hypot(next.x-v.x,next.y-v.y)||1;const n1={x:winding*(v.y-prev.y)/l1,y:-winding*(v.x-prev.x)/l1},n2={x:winding*(next.y-v.y)/l2,y:-winding*(next.x-v.x)/l2};const denom=Math.max(.08,1+n1.x*n2.x+n1.y*n2.y);const x=v.x+(n1.x+n2.x)/denom*.8,y=v.y+(n1.y+n2.y)/denom*.8;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath();ctx.clip();const A=((q.x-p.x)*(c.y-a.y)-(r.x-p.x)*(b.y-a.y))/det,B=((q.y-p.y)*(c.y-a.y)-(r.y-p.y)*(b.y-a.y))/det,C=((r.x-p.x)*(b.x-a.x)-(q.x-p.x)*(c.x-a.x))/det,D=((r.y-p.y)*(b.x-a.x)-(q.y-p.y)*(c.x-a.x))/det;ctx.transform(A,B,C,D,p.x-A*a.x-C*a.y,p.y-B*a.x-D*a.y);ctx.drawImage(img,0,0);ctx.restore()}
export function drawBook(ctx:CanvasRenderingContext2D,images:HTMLImageElement[],old:number,next=old,t=0){const W=1400,H=794,Y=103,half=700;ctx.clearRect(0,0,W,1000);const single=(i:number)=>i===0||i===29;const drawHalf=(im:HTMLImageElement,right:boolean,x:number)=>ctx.drawImage(im,right?im.width/2:0,0,im.width/2,im.height,x,Y,half,H);
if(old===next){const im=images[old];if(!im?.naturalWidth)return;if(single(old))ctx.drawImage(im,350,Y,700,H);else{ctx.fillStyle='#c3b9a0';ctx.fillRect(0,Y+5,W,H+5);ctx.drawImage(im,0,Y,W,H);const g=ctx.createLinearGradient(677,0,723,0);g.addColorStop(0,'#0000');g.addColorStop(.5,'#15171326');g.addColorStop(1,'#0000');ctx.fillStyle=g;ctx.fillRect(677,Y,46,H)}return}
const forward=next>old,dir=forward?1:-1,cover=single(old)||single(next),a=images[old],b=images[next];let spine=700;if(old===0)spine=350+350*t;if(next===0)spine=700-350*t;if(next===29)spine=700+350*t;if(old===29)spine=1050-350*t;
ctx.fillStyle='#b5ab95';ctx.fillRect(Math.max(0,spine-700),Y+7,Math.min(1400,spine+700)-Math.max(0,spine-700),H+5);
if(!single(forward?old:next))drawHalf(forward?a:b,false,spine-700);if(!single(forward?next:old))drawHalf(forward?b:a,true,spine);
const cols=64,rows=6,angle=t*Math.PI;const points:{x:number;z:number;theta:number}[]=[{x:0,z:0,theta:angle}];for(let i=1;i<=cols;i++){const u=(i-.5)/cols,theta=angle+(cover?0:Math.sin(angle)*.62*(u-.48));const prev=points[i-1];points.push({x:prev.x+Math.cos(theta)*half/cols,z:prev.z+Math.sin(theta)*half/cols,theta})}
const project=(i:number,v:number)=>{const p=points[i],scale=2600/(2600-p.z);return {x:spine+dir*p.x*scale,y:500+(v-.5)*H*scale}};
const shadowWidth=Math.sin(angle)*200;ctx.save();const shadow=ctx.createLinearGradient(spine-shadowWidth,0,spine+shadowWidth+1,0);shadow.addColorStop(0,'#0000');shadow.addColorStop(.5,`rgba(13,18,15,${Math.sin(angle)*.22})`);shadow.addColorStop(1,'#0000');ctx.fillStyle=shadow;ctx.fillRect(spine-shadowWidth,Y,shadowWidth*2,H);ctx.restore();
for(let i=0;i<cols;i++){const back=Math.cos(points[i].theta)<0,im=back?b:a;const tex=(u:number,v:number)=>{let x;if(single(back?next:old))x=forward?(back?1-u:u):(back?u:1-u);else x=forward?(back?(1-u)/2:.5+u/2):(back?.5+u/2:(1-u)/2);return {x:x*im.width,y:v*im.height}};for(let j=0;j<rows;j++){const u=i/cols,v=j/rows,u2=(i+1)/cols,v2=(j+1)/rows;const d=[project(i,v),project(i+1,v),project(i+1,v2),project(i,v2)],s=[tex(u,v),tex(u2,v),tex(u2,v2),tex(u,v2)];triangle(ctx,im,[s[0],s[1],s[2]],[d[0],d[1],d[2]]);triangle(ctx,im,[s[0],s[2],s[3]],[d[0],d[2],d[3]])}}
// One translucent light pass avoids seams between texture triangles.
ctx.beginPath();for(let i=0;i<=cols;i++){const p=project(i,0);if(!i)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}for(let i=cols;i>=0;i--){const p=project(i,1);ctx.lineTo(p.x,p.y)}ctx.closePath();ctx.fillStyle=`rgba(16,21,17,${Math.sin(angle)*.14})`;ctx.fill();ctx.strokeStyle='#c9c1aa88';ctx.lineWidth=.7;ctx.stroke();}
