"use client";
import {useEffect,useRef,useState} from 'react';
import Link from "@/components/SiteLink";
export default function AboutPage(){const [ready,setReady]=useState(false),[hover,setHover]=useState(false),[pinned,setPinned]=useState(false);const active=hover||pinned;const base=useRef<HTMLCanvasElement>(null);const canvas=useRef<HTMLCanvasElement>(null),region=useRef<HTMLDivElement>(null),pointer=useRef({x:-1,y:-1,amount:0}),target=useRef({x:-1,y:-1,amount:0});
useEffect(()=>{const image=new Image();let cancelled=false;image.onload=()=>{if(cancelled)return;const c=base.current!,ctx=c.getContext('2d')!;c.width=760;c.height=660;ctx.drawImage(image,3070,3510,760,660,0,0,760,660);const pixels=ctx.getImageData(0,0,760,660);for(let i=0;i<pixels.data.length;i+=4){const [r,g,b]=[pixels.data[i],pixels.data[i+1],pixels.data[i+2]];if(r>195&&g>185&&b>120)pixels.data[i+3]=0}ctx.putImageData(pixels,0,0)};image.src='/caoxudong-digital-garden/about/1.jpg';return()=>{cancelled=true}},[]);
useEffect(()=>{const scroll=()=>{if(location.hash==='#contact')document.getElementById('contact')?.scrollIntoView({block:'start'});else if(location.hash==='#top')window.scrollTo(0,0)};scroll();window.addEventListener('hashchange',scroll);return()=>window.removeEventListener('hashchange',scroll)},[]);
useEffect(()=>{let frame=0,cancel=false;const c=canvas.current!,gl=c.getContext('webgl',{alpha:true,antialias:false});if(!gl)return;const shader=(type:number,source:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,source);gl.compileShader(s);return s};const program=gl.createProgram()!;gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 p;varying vec2 uv;void main(){uv=(p+1.0)*.5;uv.y=1.0-uv.y;gl_Position=vec4(p,0,1);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision highp float;varying vec2 uv;uniform sampler2D paper;uniform vec2 mouse;uniform vec2 size;uniform float power;void main(){vec2 delta=(uv-mouse)*size;float d=length(delta);float radius=clamp(size.x*.05,22.0,70.0);float influence=exp(-d*d/(radius*radius));vec2 sampleUV=mouse+(uv-mouse)/(1.0+power*.42*influence);gl_FragColor=texture2D(paper,sampleUV);}`));gl.linkProgram(program);gl.useProgram(program);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const attr=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(attr);gl.vertexAttribPointer(attr,2,gl.FLOAT,false,0,0);const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
// The supplied handwriting layer is warped independently, in local character-sized areas.
const im=new Image();im.src='/caoxudong-digital-garden/about/3.png';im.onload=()=>{if(cancel)return;const sampled=document.createElement('canvas');sampled.width=2048;sampled.height=2048;const sc=sampled.getContext('2d')!;sc.imageSmoothingQuality='high';sc.drawImage(im,0,0,2048,2048);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,sampled);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);setReady(true);const draw=()=>{const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(c.width!==Math.round(r.width*dpr)||c.height!==Math.round(r.height*dpr)){c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);gl.viewport(0,0,c.width,c.height)}const p=pointer.current,t=target.current;p.x+=(t.x-p.x)*.17;p.y+=(t.y-p.y)*.17;p.amount+=(t.amount-p.amount)*.12;gl.uniform2f(gl.getUniformLocation(program,'mouse'),p.x,p.y);gl.uniform2f(gl.getUniformLocation(program,'size'),r.width,r.height);gl.uniform1f(gl.getUniformLocation(program,'power'),p.amount);gl.drawArrays(gl.TRIANGLES,0,6);frame=requestAnimationFrame(draw)};draw()};return()=>{cancel=true;cancelAnimationFrame(frame);gl.deleteTexture(tex);gl.deleteBuffer(buf);gl.deleteProgram(program)}},[]);
return <section className="about-paper-page" id="top"><div className="about-background" aria-hidden="true">{[0,1,2,3].map(i=><img key={i} src="/caoxudong-digital-garden/about/grid-background.jpg" alt=""/>)}</div><Link className="about-home" href="/caoxudong-digital-garden/">← Home / 返回主页</Link><div className="about-artboard" ref={region} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();target.current={x:(e.clientX-r.x)/r.width,y:(e.clientY-r.y)/r.height,amount:1}}} onPointerLeave={()=>target.current.amount=0}>
<img className="about-handwriting-fallback" src="/caoxudong-digital-garden/about/3.png" alt="手写自我介绍与联系方式" style={{visibility:ready?'hidden':'visible'}}/><canvas className="about-handwriting" ref={canvas} aria-label="曹旭东的手写自我介绍与联系方式" role="img"/>
<button className={'about-portrait'+(active?' is-active':'')} aria-label="显示曹旭东头像" aria-pressed={pinned} onPointerEnter={()=>{setHover(true);target.current.amount=0}} onPointerLeave={()=>setHover(false)} onFocus={()=>setHover(true)} onBlur={()=>setHover(false)} onClick={()=>setPinned(true)}><img src="/caoxudong-digital-garden/about/4.png" alt="绿色剪贴图标"/><img src="/caoxudong-digital-garden/about/5.png" alt="曹旭东头像"/></button>
<Link className="about-frog-home" href="/caoxudong-digital-garden/" aria-label="青蛙，返回主页"><canvas ref={base} aria-hidden="true"/></Link><section id="contact" className="about-contact-anchor" aria-label="联系方式"><span className="sr-only">联系我：邮箱 2475618364@qq.com；小红书：2206055171；Bilibili：蛙脑转转Dong。</span></section>
</div></section>}

