"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from "@/components/SiteLink";
import works from '@/data/scraps.json';
import PaperUnfold from './PaperUnfold';
const bins=[{id:'hazardous',en:'HAZARDOUS WASTE',zh:'有害垃圾',points:'56,286 282,248 285,90 397,100 405,272 428,283 260,350 311,392 301,786 129,749',x:23,y:38},{id:'wet',en:'WET WASTE',zh:'湿垃圾',points:'260,350 480,283 483,114 612,132 612,319 524,832 367,850 312,809',x:40,y:43},{id:'dry',en:'DRY WASTE',zh:'干垃圾',points:'495,410 697,321 706,142 848,163 838,348 879,376 750,898 665,931 527,880',x:58,y:49},{id:'recyclable',en:'RECYCLABLE WASTE',zh:'可回收垃圾',points:'755,460 944,369 961,176 1125,201 1098,402 1147,425 996,1019 763,955',x:79,y:56}];
export default function LittleScraps(){const [category,setCategory]=useState<string|null>(null),[index,setIndex]=useState(0),[phase,setPhase]=useState<'bins'|'unfold'|'paper'>('bins'),[origin,setOrigin]=useState({x:0,y:0}),[serial,setSerial]=useState(0),[revealed,setRevealed]=useState(false),[stamp,setStamp]=useState(''),[track,setTrack]=useState<{x:number;y:number;id:number}|null>(null);const cross=useRef<HTMLDivElement>(null),lastTrack=useRef(0),stageRef=useRef<HTMLDivElement>(null),returnRef=useRef<HTMLButtonElement>(null),lastBin=useRef<SVGGElement|null>(null);const selected=works.filter(w=>w.category===category),work=selected[index];
useEffect(()=>{const tick=()=>setStamp(new Date().toLocaleString('sv-SE'));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[]);
useEffect(()=>{if(!track)return;const id=setTimeout(()=>setTrack(null),600);return()=>clearTimeout(id)},[track]);
const reveal=useCallback(()=>setRevealed(true),[]);
const done=useCallback(()=>setPhase('paper'),[]);
const close=()=>{setPhase('bins');setCategory(null);requestAnimationFrame(()=>lastBin.current?.focus())};
useEffect(()=>{if(phase==='paper')returnRef.current?.focus();else if(phase==='unfold')stageRef.current?.focus()},[phase]);
const open=(id:string,node:SVGGElement)=>{lastBin.current=node;const b=node.getBoundingClientRect();setOrigin({x:b.x+b.width*.5,y:b.y+b.height*.42});setCategory(id);setIndex(0);setSerial(s=>s+1);setRevealed(false);setPhase('unfold')};
return <section className={'scraps-room phase-'+phase} aria-label="小垃圾 / Little Scraps" onKeyDown={e=>{if(e.key==='Escape'&&phase!=='bins'){e.preventDefault();close()}}} onPointerMove={e=>{cross.current?.style.setProperty('--mx',e.clientX+'px');cross.current?.style.setProperty('--my',e.clientY+'px');const now=performance.now();if(now-lastTrack.current>900&&Math.random()<.14){lastTrack.current=now;setTrack({x:Math.min(innerWidth-100,e.clientX+12),y:Math.max(24,e.clientY-50),id:Math.floor(Math.random()*9000)})}}}>
<header className="scraps-head"><Link href="/caoxudong-digital-garden/">← HOME</Link><h1>LITTLE SCRAPS <span>/ 小垃圾</span></h1><span>CAM_04 · {stamp}</span></header>
<div className="scraps-scene" aria-hidden={phase!=='bins'} inert={phase!=='bins'}><img src="/caoxudong-digital-garden/scraps/bins.jpg" alt="黑、灰、绿、蓝四个垃圾桶"/><svg viewBox="0 0 1200 1100" className="scraps-bin-targets">{bins.map((b,i)=><g role="button" tabIndex={0} key={b.id} aria-label={b.en+' / '+b.zh} onClick={e=>open(b.id,e.currentTarget)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(b.id,e.currentTarget)}}}><polygon points={b.points}/><text x={b.x*12} y={b.y*11}>[ 0{i+1} · {b.zh} ]</text></g>)}</svg></div>
<div className="scraps-classifications">{bins.map((b,i)=><span key={b.id}>0{i+1}<b>{b.en}</b>{b.zh}</span>)}</div>
<div className="scraps-camera-lines" aria-hidden="true"/><div ref={cross} className="scraps-crosshair" aria-hidden="true"/>{track&&<div key={track.id} className="scraps-tracking" style={{left:track.x,top:track.y}} aria-hidden="true"><span>TRACK_{track.id}</span></div>}
{phase!=='bins'&&<div ref={stageRef} tabIndex={-1} className="scraps-sheet-stage" onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button,video'));if(!nodes.length){e.preventDefault();return}const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}} role="dialog" aria-modal="true" aria-label={work?.title}>
{phase==='unfold'&&<PaperUnfold key={serial} origin={origin} onReveal={reveal} onDone={done}/>}
{(phase==='paper'||revealed)&&work&&<article key={serial} className="scraps-paper"><header><span>{bins.find(b=>b.id===category)?.en} / {String(index+1).padStart(2,'0')}</span><button ref={returnRef} onClick={close}>返回 ↗</button></header><div className="scraps-paper-scroll"><h2>{work.title.match(/^[^A-Za-z0-9]+/)?.[0]}<span>{work.title.replace(/^[^A-Za-z0-9]+/,'')}</span></h2><dl><div><dt>作者</dt><dd>{work.author}</dd></div><div><dt>作品形式</dt><dd>{work.format}</dd></div></dl><div className="scraps-work-media">{work.media.map((m,i)=><figure key={m.src}>{m.type==='video'?<video src={m.src} controls playsInline preload="metadata" aria-label={work.title+'视频'}/>:<img src={m.src} alt={work.title+' · '+(i+1)} loading={i>1?'lazy':'eager'}/>}</figure>)}</div>{work.description&&<p className="scraps-description">{work.description}</p>}</div><footer><span>{String(index+1).padStart(2,'0')} / {String(selected.length).padStart(2,'0')}</span><span className="scraps-next-hint"><span>点击 NEXT </span><span>查看下一个小垃圾</span></span><button className="scraps-next" disabled={phase!=='paper'} onClick={()=>{setOrigin({x:innerWidth/2,y:innerHeight/2});setIndex(i=>(i+1)%selected.length);setSerial(s=>s+1);setRevealed(false);setPhase('unfold')}}>NEXT →</button></footer></article>}
</div>}
<footer className="scraps-system"><span>● LIVE / OBJECT RECOGNITION</span><span>ARCHIVE / 04</span></footer>
</section>}

