"use client";
import {useEffect,useRef,useState} from 'react';
import Link from "@/components/SiteLink";
import movies from '@/data/movies.json';
export default function MovieRoom(){const [index,setIndex]=useState(0),[opened,setOpened]=useState(false),[assembling,setAssembling]=useState(false),[expanded,setExpanded]=useState(false),[transition,setTransition]=useState(false);const noteCanvas=useRef<HTMLCanvasElement>(null),noteRaf=useRef(0),pinned=useRef(false),hideTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const canvas=useRef<HTMLCanvasElement>(null),poster=useRef<HTMLImageElement>(null),note=useRef<HTMLElement>(null),scroll=useRef<HTMLDivElement>(null),locked=useRef(false),raf=useRef(0),current=useRef(0);const movie=movies[index];
const snapshot=(includePoster=true)=>{const c=document.createElement('canvas');c.width=innerWidth;c.height=innerHeight;const ctx=c.getContext('2d')!;const im=poster.current;if(includePoster&&im?.naturalWidth){const r=im.getBoundingClientRect();ctx.drawImage(im,r.x,r.y,r.width,r.height)}if(note.current){const r=note.current.getBoundingClientRect();ctx.fillStyle='#c4c4c0';ctx.fillRect(r.x,r.y,r.width,r.height);ctx.fillStyle='#151f76';ctx.fillRect(r.x+4,r.y+4,r.width-8,27);ctx.fillStyle='#faf9f1';ctx.fillRect(r.x+7,r.y+36,r.width-14,r.height-43);ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.width,r.height);ctx.clip();note.current.querySelectorAll<HTMLElement>('[data-ink]').forEach(el=>{const box=el.getBoundingClientRect(),style=getComputedStyle(el);ctx.font=`${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;ctx.fillStyle=style.color;ctx.textBaseline='top';const lh=parseFloat(style.lineHeight)||18;let x=box.x,y=box.y;for(const char of el.textContent??''){const w=ctx.measureText(char).width;if(char==='\n'||x+w>box.right){x=box.x;y+=lh;if(char==='\n')continue}ctx.fillText(char,x,y);x+=w}});ctx.restore()}return c};
const dissolve=(source:HTMLCanvasElement,incoming:boolean)=>new Promise<void>(resolve=>{const c=canvas.current!,ctx=c.getContext('2d')!;c.width=innerWidth;c.height=innerHeight;const start=performance.now(),duration=incoming?640:460;const tick=(now:number)=>{const p=Math.min(1,(now-start)/duration),amount=incoming?1-p:p;ctx.clearRect(0,0,c.width,c.height);const tile=10;ctx.imageSmoothingEnabled=false;ctx.globalAlpha=1-amount;for(let y=0;y<source.height;y+=tile)for(let x=0;x<source.width;x+=tile){const seed=Math.sin(x*12.98+y*78.23)*43758.54,random=seed-Math.floor(seed);const dx=Math.sin(random*18)*amount*65,dy=incoming?amount*amount*(100+random*150):-amount*amount*(30+random*95);const size=tile*(1-amount*.6);ctx.drawImage(source,x,y,tile,tile,x+dx,y+dy,size,size)}ctx.globalAlpha=1;if(p<1)raf.current=requestAnimationFrame(tick);else{ctx.clearRect(0,0,c.width,c.height);resolve()}};raf.current=requestAnimationFrame(tick)});
const change=async(dir:number)=>{if(locked.current)return;locked.current=true;cancelAnimationFrame(noteRaf.current);setAssembling(false);if(noteCanvas.current)noteCanvas.current.getContext('2d')?.clearRect(0,0,innerWidth,innerHeight);const next=(current.current+dir+movies.length)%movies.length;const image=new Image();image.src=movies[next].poster;await image.decode().catch(()=>{});const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced){const before=snapshot();setTransition(true);await dissolve(before,false)}current.current=next;setIndex(next);setExpanded(false);await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));if(scroll.current)scroll.current.scrollTop=0;if(!reduced)await dissolve(snapshot(),true);setTransition(false);locked.current=false};
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();void change(e.key==='ArrowRight'?1:-1)}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);cancelAnimationFrame(raf.current)}},[]);
const cancelHide=()=>{if(hideTimer.current)clearTimeout(hideTimer.current)};
const show=()=>{cancelHide();if(locked.current)return;if(!opened){setAssembling(true);setOpened(true)}};
const hide=()=>{cancelHide();hideTimer.current=setTimeout(()=>{if(!pinned.current)setOpened(false)},280)};
const closeNote=()=>{pinned.current=false;cancelHide();setOpened(false)};
useEffect(()=>{if(!opened)return;const c=noteCanvas.current!,ctx=c.getContext('2d')!;c.width=innerWidth;c.height=innerHeight;const source=snapshot(false),r=note.current!.getBoundingClientRect(),start=performance.now();const tick=(now:number)=>{const t=Math.min(1,(now-start)/720),amount=Math.pow(1-t,3);ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;for(let y=Math.floor(r.top);y<r.bottom;y+=8)for(let x=Math.floor(r.left);x<r.right;x+=8){const seed=Math.sin(x*12.989+y*78.23)*43758.54,rand=seed-Math.floor(seed);ctx.globalAlpha=Math.min(1,t*3);ctx.drawImage(source,x,y,8,8,x+Math.cos(rand*20)*amount*140,y+(90+rand*170)*amount,8*(1-amount*.5),8*(1-amount*.5))}ctx.globalAlpha=1;if(t<1)noteRaf.current=requestAnimationFrame(tick);else{ctx.clearRect(0,0,c.width,c.height);setAssembling(false)}};noteRaf.current=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(noteRaf.current);ctx.clearRect(0,0,c.width,c.height)}},[opened]);
useEffect(()=>()=>{if(hideTimer.current)clearTimeout(hideTimer.current)},[]);
const review=expanded?movie.review:Array.from(movie.review).slice(0,200).join('');return <section className={'movie-room'+(transition?' movie-changing':'')} onClick={e=>{if((e.target as Element).closest('a,button,.movie-note,.movie-poster'))return;void change(e.clientX<innerWidth/2?-1:1)}} aria-label="最近看的一些电影"><div className="movie-tile-wall" aria-hidden="true"/><div className="movie-wall-light" aria-hidden="true"/><div className="movie-wall-sign" aria-hidden="true"><span>3</span></div><nav className="movie-nav"><Link href="/caoxudong-digital-garden/">Home / 返回主页</Link><Link href="/caoxudong-digital-garden/life">Back / 返回上一级</Link></nav><button className="movie-poster" aria-label={'打开《'+movie.title+'》电影信息'} onPointerEnter={show} onPointerLeave={hide} onFocus={show} onBlur={hide} onClick={()=>{pinned.current=true;show()}}><img ref={poster} src={movie.poster} alt={movie.title+'海报'}/></button>{opened&&<aside className={'movie-note'+(assembling?' note-assembling':'')} onPointerEnter={cancelHide} onPointerLeave={hide} ref={note} aria-label="电影信息窗口"><header><span data-ink>▤ {movie.title} — Notepad</span><button aria-label="关闭电影信息" onClick={closeNote}>×</button></header><div className="movie-note-scroll" ref={scroll} onScroll={e=>{const el=e.currentTarget;note.current?.style.setProperty("--scroll",String(el.scrollTop/Math.max(1,el.scrollHeight-el.clientHeight)))}}><h1 data-ink>{movie.title}</h1>{movie.info.map((s,i)=><p data-ink className="movie-meta" key={i}>{s}</p>)}{movie.review&&<><div className="movie-rule"/><p data-ink className="movie-review">{review}</p>{!expanded&&Array.from(movie.review).length>200&&<button className="movie-read-more" onClick={()=>setExpanded(true)}>继续阅读</button>}</>}</div><div className="movie-scroll-rail" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();if(scroll.current)scroll.current.scrollTop=(e.clientY-r.top)/r.height*(scroll.current.scrollHeight-scroll.current.clientHeight)}} aria-hidden="true"><span/></div></aside>}<span className="movie-switch-hint">CLICK SIDES / ← → TO SWITCH</span><canvas className="movie-note-particles" ref={noteCanvas} aria-hidden="true"/><canvas className="movie-particles" ref={canvas} aria-hidden="true"/></section>}
