"use client";
import {useEffect,useRef,useState} from 'react';
import songs from '@/data/songs.json';
function Marquee({text}:{text:string}){const ref=useRef<HTMLDivElement>(null);const [overflow,setOverflow]=useState(false);useEffect(()=>{const el=ref.current!;const measure=()=>setOverflow((el.firstElementChild?.scrollWidth||0)>el.clientWidth+1);const observer=new ResizeObserver(measure);observer.observe(el);measure();return()=>observer.disconnect()},[text]);return <div ref={ref} className={'mp3-marquee'+(overflow?' is-overflow':'')} aria-label={text}><div className="mp3-marquee-track"><span>{text}</span>{overflow&&<span aria-hidden="true">{text}</span>}</div></div>}
export default function MusicPlayer({onClose}:{onClose:()=>void}){
 const [index,setIndex]=useState(0),[dim,setDim]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null),close=useRef<HTMLButtonElement>(null);const song=songs[index];
 useEffect(()=>{close.current?.focus();return()=>{if(timer.current)clearTimeout(timer.current)}},[]);
 const change=(dir:number)=>{if(timer.current)return;setDim(true);timer.current=setTimeout(()=>{setIndex(i=>(i+dir+songs.length)%songs.length);setDim(false);timer.current=null},140)};
 return <div className="music-window" role="dialog" aria-label="Music / 最近常哼的歌" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose()}}}>
 <div className="mine-titlebar"><span>♫ Music / 最近常哼的歌</span><button ref={close} aria-label="关闭音乐播放器" onClick={onClose}>×</button></div>
 <div className="mp3-body"><div className={'mp3-screen'+(dim?' is-dim':'')}><div className="mp3-screen-main"><img className="mp3-cover" src={song.cover} alt={song.title+'封面'}/><div className="mp3-copy" aria-live="polite"><div className="mp3-title"><Marquee key={song.title} text={song.title}/></div><div className="mp3-artist"><Marquee key={song.artist} text={song.artist}/></div></div></div><div className="mp3-progress" aria-hidden="true"><span>2:05</span><i><b/></i><span>4:47</span></div></div>
 <div className="mp3-wheel"><a className="mp3-music" href={song.url} target="_blank" rel="noopener noreferrer" aria-label={'在网易云打开'+song.title}>MUSIC</a><button className="mp3-prev" onClick={()=>change(-1)} aria-label="上一首"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M5 5h4v22H5zM27 5L10 16l17 11z"/></svg></button><button className="mp3-next" onClick={()=>change(1)} aria-label="下一首"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M23 5h4v22h-4zM5 5l17 11L5 27z"/></svg></button><a className="mp3-play" href={song.url} target="_blank" rel="noopener noreferrer" aria-label={'播放'+song.title}><svg viewBox="0 0 44 32" aria-hidden="true"><path d="M2 5l17 11L2 27zM23 5h6v22h-6zM34 5h6v22h-6z"/></svg></a><div className="mp3-center" aria-hidden="true"/></div></div></div>
}
