"use client";
import {useEffect,useRef,useState} from 'react';
import Link from "@/components/SiteLink";
import PhotoWater from './PhotoWater';
import {drawBook} from '@/lib/drawBook';
const intro='《失向》从一个雨夜开始：街灯下，一群本该追随月光完成“婚飞”的白蚁，却被更亮的人造光吸引，飞向了错误的方向。这个意外的画面，恰好对应了当时毕业季、梅雨季与个人迷茫交叠的状态。摄影因此变成了一种整理情绪的方式，也让“失去方向”从昆虫的本能偏差，慢慢变成了一种关于人的隐喻。';
const url=(i:number)=>'/caoxudong-digital-garden/photography/'+String(i).padStart(2,'0')+'.webp';
export default function Photography(){const [mode,setMode]=useState<'shelf'|'reading'|'video'>('shelf'),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[exiting,setExiting]=useState(false);const canvas=useRef<HTMLCanvasElement>(null),images=useRef<HTMLImageElement[]>([]),frame=useRef(0),returnMode=useRef<'shelf'|'reading'>('shelf'),bookButton=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLDivElement>(null);const state=useRef({page:0,busy:false});
const paint=(n:number)=>{const c=canvas.current;if(c)drawBook(c.getContext('2d')!,images.current,n)};
useEffect(()=>{images.current=Array.from({length:30},(_,i)=>{const im=new Image();im.src=url(i);im.onload=()=>{if(state.current.page===i&&!state.current.busy)paint(i)};return im});return()=>cancelAnimationFrame(frame.current)},[]);
const turn=(dir:number)=>{const old=state.current.page,next=old+dir;if(state.current.busy||next<0||next>29||!images.current[next]?.naturalWidth)return;state.current.busy=true;setBusy(true);const start=performance.now();const tick=(now:number)=>{const p=Math.min(1,(now-start)/1400),t=p*p*p*(p*(p*6-15)+10);if(canvas.current)drawBook(canvas.current.getContext('2d')!,images.current,old,next,t);if(p<1)frame.current=requestAnimationFrame(tick);else{state.current={page:next,busy:false};setPage(next);setBusy(false);paint(next)}};frame.current=requestAnimationFrame(tick)};
const closeVideo=()=>{setExiting(true);setTimeout(()=>{setMode(returnMode.current);setExiting(false)},300)};
const close=()=>{cancelAnimationFrame(frame.current);state.current.busy=false;setBusy(false);setExiting(true);setTimeout(()=>{setMode('shelf');setExiting(false);bookButton.current?.focus()},380)};
useEffect(()=>{if(mode==='reading'){paint(state.current.page);dialog.current?.focus();const timer=setTimeout(()=>{if(state.current.page===0)turn(1)},650);return()=>clearTimeout(timer)}},[mode]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(mode==='shelf')return;if(e.key==='Escape'){if(mode==='video')closeVideo();else close()}if(mode==='reading'&&['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();turn(e.key==='ArrowRight'?1:-1)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mode]);
return <section className={'photography-room mode-'+mode+(exiting?' is-closing':'')}><PhotoWater/><div className="photo-gauze"/><Link className="photo-back" href="/caoxudong-digital-garden/life" aria-label="返回日常桌面">←</Link><header className="photo-copy"><p>Photography / 摄影</p><h1>失向</h1><p className="photo-meta">2026 · 摄影 / 书本设计</p><p className="photo-intro">{intro}</p></header><div className="photo-shelf"><button ref={bookButton} className="physical-book first-book" onClick={()=>{state.current.page=0;setPage(0);setMode('reading')}} aria-label="打开《失向》摄影书"><span className="book-pages"/><img className="book-cover" src={url(0)} alt="《失向》真实封面"/></button><div className="physical-book companion-book" aria-label="未开放的空白摄影册"><span className="book-pages"/><span className="book-cover"><span>会有更多的吧……</span></span></div></div>
{mode==='reading'&&<div className="photo-reading" role="dialog" aria-modal="true" aria-label="阅读《失向》" tabIndex={-1} ref={dialog} onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="open-photo-book" onClick={e=>e.stopPropagation()}><canvas ref={canvas} width={1400} height={1000} aria-label={'书页 '+page}/><button className="page-prev" aria-label="上一页" disabled={busy||page===0} onClick={()=>turn(-1)}>‹</button><button className="page-next" aria-label="下一页" disabled={busy||page===29} onClick={()=>turn(1)}>›</button><span className="book-pagination">{page===0?'封面':page===29?'封底':String(page+1).padStart(2,'0')}</span></div></div>}
<button className="photo-video-button" aria-label="观看《失向》翻书视频" onClick={()=>{returnMode.current=mode==='reading'?'reading':'shelf';setMode('video')}}><img src={url(0)} alt=""/><span>▷</span></button>{mode==='video'&&<div className="photo-video-layer" role="dialog" aria-modal="true" aria-label="《失向》翻书视频" onClick={e=>{if(e.target===e.currentTarget)closeVideo()}}><button autoFocus className="photo-video-close" aria-label="关闭视频" onClick={()=>closeVideo()}>×</button><video src="/caoxudong-digital-garden/photography/film.mp4" controls autoPlay playsInline/></div>}</section>}
